// <auto-generated />
using System;
using DATN_70.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DATN_70.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407111019_OpDB")]
    partial class OpDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DATN_70.Models.Entities.ChiTietGioHang", b =>
                {
                    b.Property<string>("ChiTietGioHangID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ChiTietSanPhamID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("GioHangID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("ChiTietGioHangID");

                    b.HasIndex("ChiTietSanPhamID");

                    b.HasIndex("GioHangID");

                    b.ToTable("ChiTietGioHangs");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.ChiTietSanPham", b =>
                {
                    b.Property<string>("ChiTietSanPhamID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<decimal>("GiaNiemYet")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("KichCoID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MauID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SanPhamID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoLuongTonKho")
                        .HasColumnType("int");

                    b.HasKey("ChiTietSanPhamID");

                    b.HasIndex("KichCoID");

                    b.HasIndex("MauID");

                    b.HasIndex("SanPhamID");

                    b.ToTable("ChiTietSanPhams");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.ChiTietThanhToan", b =>
                {
                    b.Property<string>("ChiTietThanhToanID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("HoaDonID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("MaThamChieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhuongThucThanhToanID")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ChiTietThanhToanID");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("PhuongThucThanhToanID");

                    b.ToTable("ChiTietThanhToans");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.DanhMuc", b =>
                {
                    b.Property<string>("DanhMucID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DanhMucID");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.DiaChi", b =>
                {
                    b.Property<string>("DiaChiID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("KhachHangID")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LaMacDinh")
                        .HasColumnType("bit");

                    b.Property<string>("PhuongXa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuanHuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoaiNhan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhThanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DiaChiID");

                    b.HasIndex("KhachHangID");

                    b.ToTable("DiaChis");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.GioHang", b =>
                {
                    b.Property<string>("GioHangID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaiKhoanID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("GioHangID");

                    b.HasIndex("TaiKhoanID")
                        .IsUnique();

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.HoaDon", b =>
                {
                    b.Property<string>("HoaDonID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("DiaChiID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KhachHangID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KhuyenMaiID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LoaiGiaoDich")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TongTienGiamGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TongTienVAT")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("HoaDonID");

                    b.HasIndex("DiaChiID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("KhuyenMaiID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.HoaDonChiTiet", b =>
                {
                    b.Property<string>("HoaDonChiTietID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ChiTietSanPhamID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("HoaDonID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<decimal>("MucVAT")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("TienVAT")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("HoaDonChiTietID");

                    b.HasIndex("ChiTietSanPhamID");

                    b.HasIndex("HoaDonID");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.KhachHang", b =>
                {
                    b.Property<string>("KhachHangID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TaiKhoanID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KhachHangID");

                    b.HasIndex("TaiKhoanID")
                        .IsUnique();

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.KhuyenMai", b =>
                {
                    b.Property<string>("KhuyenMaiID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("GiaTriToiThieuApDung")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhanTramChietKhau")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("KhuyenMaiID");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.KhuyenMaiSanPham", b =>
                {
                    b.Property<string>("KhuyenMaiID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SanPhamID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KhuyenMaiID", "SanPhamID");

                    b.HasIndex("SanPhamID");

                    b.ToTable("KhuyenMaiSanPhams");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.KichCo", b =>
                {
                    b.Property<string>("KichCoID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KichCoID");

                    b.ToTable("KichCos");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.Mau", b =>
                {
                    b.Property<string>("MauID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MauID");

                    b.ToTable("Maus");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.NhanVien", b =>
                {
                    b.Property<string>("NhanVienID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhanViec")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TaiKhoanID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NhanVienID");

                    b.HasIndex("TaiKhoanID")
                        .IsUnique();

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.PhuongThucThanhToan", b =>
                {
                    b.Property<string>("PhuongThucThanhToanID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HinhURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("KieuThanhToan")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("PhuongThucThanhToanID");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.SanPham", b =>
                {
                    b.Property<string>("SanPhamID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChatLieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DanhMucID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MucVAT")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThuongHieuID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SanPhamID");

                    b.HasIndex("DanhMucID");

                    b.HasIndex("ThuongHieuID");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<string>("TaiKhoanID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTroID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TaiKhoanID");

                    b.HasIndex("VaiTroID");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.ThuongHieu", b =>
                {
                    b.Property<string>("ThuongHieuID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LogoURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ThuongHieuID");

                    b.ToTable("ThuongHieus");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.VaiTro", b =>
                {
                    b.Property<string>("VaiTroID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VaiTroID");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.ChiTietGioHang", b =>
                {
                    b.HasOne("DATN_70.Models.Entities.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("ChiTietSanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_70.Models.Entities.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("GioHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.ChiTietSanPham", b =>
                {
                    b.HasOne("DATN_70.Models.Entities.KichCo", "KichCo")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("KichCoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_70.Models.Entities.Mau", "Mau")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MauID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_70.Models.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("SanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KichCo");

                    b.Navigation("Mau");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.ChiTietThanhToan", b =>
                {
                    b.HasOne("DATN_70.Models.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_70.Models.Entities.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("PhuongThucThanhToanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.DiaChi", b =>
                {
                    b.HasOne("DATN_70.Models.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.GioHang", b =>
                {
                    b.HasOne("DATN_70.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("GioHang")
                        .HasForeignKey("DATN_70.Models.Entities.GioHang", "TaiKhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.HoaDon", b =>
                {
                    b.HasOne("DATN_70.Models.Entities.DiaChi", "DiaChi")
                        .WithMany("HoaDons")
                        .HasForeignKey("DiaChiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_70.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DATN_70.Models.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhuyenMaiID");

                    b.HasOne("DATN_70.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiaChi");

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.HoaDonChiTiet", b =>
                {
                    b.HasOne("DATN_70.Models.Entities.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("ChiTietSanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_70.Models.Entities.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.KhachHang", b =>
                {
                    b.HasOne("DATN_70.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("DATN_70.Models.Entities.KhachHang", "TaiKhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.KhuyenMaiSanPham", b =>
                {
                    b.HasOne("DATN_70.Models.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany("KhuyenMaiSanPhams")
                        .HasForeignKey("KhuyenMaiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_70.Models.Entities.SanPham", "SanPham")
                        .WithMany("KhuyenMaiSanPhams")
                        .HasForeignKey("SanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.NhanVien", b =>
                {
                    b.HasOne("DATN_70.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanVien")
                        .HasForeignKey("DATN_70.Models.Entities.NhanVien", "TaiKhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.SanPham", b =>
                {
                    b.HasOne("DATN_70.Models.Entities.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATN_70.Models.Entities.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("ThuongHieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.TaiKhoan", b =>
                {
                    b.HasOne("DATN_70.Models.Entities.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("VaiTroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.ChiTietSanPham", b =>
                {
                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.DiaChi", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietThanhToans");

                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.KhuyenMai", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("KhuyenMaiSanPhams");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.KichCo", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.Mau", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.PhuongThucThanhToan", b =>
                {
                    b.Navigation("ChiTietThanhToans");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.SanPham", b =>
                {
                    b.Navigation("ChiTietSanPhams");

                    b.Navigation("KhuyenMaiSanPhams");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("GioHang")
                        .IsRequired();

                    b.Navigation("KhachHang")
                        .IsRequired();

                    b.Navigation("NhanVien")
                        .IsRequired();
                });

            modelBuilder.Entity("DATN_70.Models.Entities.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DATN_70.Models.Entities.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
